/**
 * Supabase connection for optional cloud sync.
 * Generated by scripts/generate-sync-config.mjs — do not edit by hand.
 * Run `npm run sync:config` to refresh from `.env`.
 */
export const SUPABASE_URL = "https://gtmsuhxnvkowaeaoqypl.supabase.co"
export const SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imd0bXN1aHhudmtvd2FlYW9xeXBsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Nzk0MDIyODEsImV4cCI6MjA5NDk3ODI4MX0.y7PxCqovf33pW_t7WDvg3EkmGLXJlzlW18-_XaLO8tk"

export function isSyncConfigured() {
  return Boolean(SUPABASE_URL && SUPABASE_ANON_KEY)
}
